name: Build code, run unittest, run SAST, run SCA, DAST security scan
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on source code
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven cloud
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=javaprojectreachability -Dsonar.organization=ajvan2808 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run SCA scan on source code
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK: ${{ secrets.SNYK }}
  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST on source code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: ZAP scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
